### ISSUE TITLE
Release for Solr-7.2.1

### ISSUE THREAD

**Issue by modassar81** [tballison/lucene-addons#29]
Hi Tim,

I am migrating to Solr-7.2.1 from Solr-6.5.1. Kindly let me know if you are planning to release lucene-addons for Solr-7.2.1. I tried and could not build it with `6.6-0.1 branch` successfully.

Thanks,
Modassar

**Comment by modassar81** [comment]
Hi Tim,

Kindly share your plan for releasing lucene-addons for Solr-7.2.1.

Thanks,
Modassar

**Comment by tballison** [comment]
Sorry for not responding.  I have to add back in the SlowFuzzyQuery because that was removed in 7.x, and it allows for a fuzzy query with an edit distance > 2...which is critical for the parser (from my perspective).  The rest should be fairly straightforward.  I'm hoping to get to this in the next week or two.  Please do keep pinging me if I don't. :)

**Comment by tballison** [comment]
https://issues.apache.org/jira/browse/SOLR-11976 is bit of a blocker.  I can try to do a workaround for now...but ugh...

**Comment by tballison** [comment]
Updated 6.2 to Solr's master and then refactored back to 7.2.1.  Let me know if there are any surprises!
